### ISSUE TITLE
Possible Unwinnable Seed

### ISSUE THREAD

**Issue by BrilliantInsanity** [mcgrew/dwrandomizer#1]
(https://github.com/mcgrew/dwrandomizer/files/60008/DWRandomizer.242119881.ctepwrmw.PRG0.-.Copy.nes.txt)

Renamed the .nes file as a .txt so I could attach it so you could view the seed yourself and confirm in case I've just overlooked something.

Using version .93 (current latest).  

The places I've gone to check:  Erdrick's cave (leads to Swamp cave Northern stairwell,
, swamp cave southern exit leads to swamp cave northern Tunnel Overworld).   Checked all other caves and entrances on Intial island, and couldnt find an exit that leads to southern swamp cave overworld exit.  Only place I haven't checked is Garin cave in Garinham, but that town is on the second island, as I have checked all of the other towns and none of them are Garinham.

Furthermore, some other issues that don't make the game unwinnable that may be worth looking into: I obtained multiple Gwailyn's Loves and Staff of rain, etc. as I looted the chests they were placed in multiple times.  As these items cannot be dropped or sold when you have duplicates it can ruin your inventory space very quickly.  Recommend at the least that you remove Gwailyn's Love from chest loot, especially if you aren't going to relocate Gwailyn.

Note: this wouldn't be an issue if i hadn't been going back through caves multiple times to make sure I didn't overlook a potential exit to get to the south island, but in the process I did end up opening the chests that had respawned forgetting what was inside.

**Comment by mcgrew** [comment]
The swamp cave issue was fixed in 0.9.3, but there was an issue with the initial binary (exe) that was uploaded. Download a new copy in order to correct this. Sorry about that.

Gwaelin's Love is being removed from the chest pool in 0.9.4, so that will no longer be an issue (it was mostly a joke anyway). The Staff of Rain is an assembly level problem, as the chest was originally only obtainable once, so there is no check for that. I'm not sure if/when that will be fixed, but I am aware of it.
