### ISSUE TITLE
Calculate enemy XP based on difficulty

### ISSUE THREAD

**Issue by mcgrew** [mcgrew/dwrandomizer#11]
Enemy experience should be calculated based on its difficulty so that experience drops reflect new abilities.

**Comment by Kronoan** [comment]
Sounds like a good idea! So if an enemy doesn't use spells or abilities it gives less EXP than normal, if they have like Hurtmore or Strong Fire Breath they give like 20% bonus exp. :)

**Comment by Niamek** [comment]
I'm not sure if that's a good idea because some spell will make some enemies easier, while the same spell will makes other enemies harder.

Heal for instance can make enemies easier(for example Green Dragon) because you usually deal more than 30 damage to them and an attack from them is much more dangerous/harder. I often got little life remaining and got saved by a heal. But on a weak enemy like Drakee, it can make them unbeatable at low levels since they basically restore their whole life.

**Comment by mcgrew** [comment]
I've thought about stuff like that, which is why I haven't implemented this yet. It may be needed for chaos mode though, depending on what goes along with that.

**Comment by mcgrew** [comment]
After some thought I've decided against this. I may reopen this issue if it seems like a good idea for chaos mode, but for now it seems unnecessary.
