### ISSUE TITLE
Swamp around Tantegel can lead to very bad seeds

### ISSUE THREAD

**Issue by VampireValik** [mcgrew/dwrandomizer#60]
Here's a "fun" seed.
Flags: ACDGIMPRTWZf
Seed: 1329829782
Character name: Z

Tantegel starts in the middle of a large swamp. There is only enough HP to make it to the 2 forest tiles south east. The enemies on those tiles: Warlock, Skeleton, Magician, Metal Scorpion, Red Slime. I ran into a regular Scorpion one step away from Tantegel once. I was unable to kill it. 

I spent 15 minutes trying to find Red Slimes so I could grind levels. Level 2 gave 0 HP. Level 3 gave 3 HP; not enough to make it away from Tantegel. At the rate I was finding Red Slimes it was going to take another 15 minutes before I could level up again with no guarantee I would get enough health to escape the sawmp. I gave up at that point.

While this seed is by no means impossible it starts out incredibly tedious. The tedium seems very easy for the randomizer to prevent. Three simple solutions that occur to me off the top of my head:

1. Never spawn Tantegel in a swamp.
2. If Tantegel is going to spawn in a swamp, have some checks in place so that the player can get away from Tantegel at starting health. I would have been fine getting out of the swamp with 1 HP and being able to explore a little bit. Spending 15 minutes dying over and over and only being able to walk to 2 tiles is not fun. Especially when hitting level 3 still wasn't enough HP to get out of the swamp.
3. If Tantegel is going to spawn in big swamps the player can't initially walk out of then force Tantegel to always have a 1 tile border of non-swamp land so the player can grind a little bit. I would have been fine grinding to level 4 if I could have done so in 5 minutes, not 15.

**Comment by Niamek** [comment]
This has already been discussed before: #12 

If it's not fun for you, it's certainly fun for other people like me. I disagree with all of the three suggestions.

The easy fix would be to create an another randomized rom.

Thanks for the seed! I'll be sure to try it out at some point. 👍

**Comment by VampireValik** [comment]
Thank you for the reference. I searched but missed that issue.

Can you elaborate why a seed like this is fun? To me it robs the seed of everything that makes the randomizer great. Instead of being an open world exploration and decision making game it becomes a linaer grindfest for the first 25+ minutes or however long it takes to get enough HP to make it out of the swamp.

**Comment by Niamek** [comment]
In my point of view, it's all about what you like in Dragon Warrior.

Some people like me like it because It's an added challenge. And personally, I like the fact you're on a "timer" and practically praying to meet an enemy early enough. You could say that after that long grind fest, you begin the famous open world exploration and decision making game that you like. What's cool about that is that if you don't have any healing source, you have a different situation that if you have "simply left" tantengel. Thus you need to be very careful with enemies and finding a town is a top priority (more important than regular seed). You could say dynamics changed! 

Also, when you get levels, generally, it will be easier to survive or to kill enemies. It's just a matter of time. :)

What I like about Dragon warrior is the open world exploration like you. But _also_ the difficulty to survive that comes with it. Swamp seed just crank that to the max. After escaping the swamp, even with 1 health point, it's now the exploring part which you and I like. :) Not to mention that if you get the heal spell, it's now not a swamp seed anymore.

I also think these swamp seeds ensure some variety from the randomizer. Some times we have linear maps (I already had Tatengel stuck in a corner. So only one direction to explore), sometimes we have swamp seed where we die a lot. Sometimes we have totally Open seeds. Sometimes we have open seeds with everything stuck in a corner...(Never saw that happen, but it's a possibility I assume)  And to add that, sometimes you have open seeds with impossible enemies. Or a mix of all of that!

If it's the death that bother you, The swamp is not the only thing that makes seeds very long. I've raced one seed where the first to finish took him about 2 hours and it wasn't a swamp seed. It was that long because almost, if not all, enemies could kill you in an instant with no spot to grind level real fast and towns very hard to find...  And I've seen a swamp race that took around the same time as well.

It's just a different mindset. I won't race a swamp seed if after 30 minutes I've made no progress at all. But often you'd do progress and eventually get out. :)

Swamp seed is indeed not for everyone and probably not race friendly. But they are still fun to have around from time to time. They are very rare, so it's not a big deal. :)

**Comment by VampireValik** [comment]
Is it really challenge, though? I don't think it's challenge. Unless you count "test of patience" as a challenge. It's not difficult to walk into a swamp and die or find an enemy that can be killed repeating the process ad nauseum. There's nothing challenging about doing the exact same inputs over and over because those are the only possible inputs that will result in any form of progression.

I will agree that a challenge would be making it out of the swamp with 1 HP and needing to find a town to heal. See suggestion 2 in my original post which covers that. That's not what happened in the seed I found, though. I found a seed where I don't get to play the game until at least 25 minutes in. That's assuming that level 4 gives useful stats, be it a strength boost to kill something other than a slime or enough HP to make it out of the swamp.

I don't think the mentality "they are very rare, so it's not a big deal" is a very healthy one. I'm sure at some point in the randomizer's life unbeatable seeds were very rare yet I have no doubt mcgrew worked to eliminate those. I also have no doubt there's a subset of people out there who'd love to try their hand at an unbeatable seed just to see if they can beat it. That doesn't mean unbeatable seeds should ever show up, though. What if this was somebody's first seed? There's a good chance this would turn them off doing more if they weren't too familiar with how good seeds can be. 

Ultimately this is up to mcgrew, of course. Personally I'm fine if he thinks my second suggestion is a good compromise. It still gives the challenge of making it out of the swamp with low health but still lets the game be played. 

Also, as a fun ancedote, you say swamp seeds are "very rare". I've generated 6 seeds so far and Tantegel has been surrounded by swamp in 3 of them. Obviously only one of them has been a large swamp. The others were just small puddles by comparison. Still, from what I'm seeing so far, Swamp Tantegel is pretty common for me.

**Comment by mcgrew** [comment]
Yeah, this has already been discussed in the community and the consensus is that this possibility should not be removed. 2.0 even has an option that makes this far more likely.

Like Niamek said, the best solution in this case is to generate a new seed if this isn't your thing. Be sure to share it on Discord though - there are plenty of people who seek out seeds like this.
