### ISSUE TITLE
Glitched object shuffled into treasure chest 

### ISSUE THREAD

**Issue by githubbalicious** [mcgrew/dwrandomizer#86]
Using v2.0.6 I got a glitched chest in Garin's Grave using seed 12345 and CDGMPVWXZ flags.
Chest displays "Sword Magician" item and awards a Dragon Scale in inventory. 
The Chest does not disappear when taken and can display different glitched contents.  Played using FCEUX 2.2.3
![sword magican](https://user-images.githubusercontent.com/49744501/56341667-c679ec80-6183-11e9-8656-6de2158196af.png)

**Comment by mcgrew** [comment]
This isn't a bug caused by the randomizer. It can happen in the original game under certain conditions, but the randomizer does make this more common. It happens when you open more than 8 chests without stepping onto the overworld.

The item stated in the message isn't the actual item you get. This is something I may try to fix eventually, but it's very low priority since it's a bug with the original game and doesn't really effect gameplay.
